services:
  ex_scraping:
    build: ./
    tty: true
    init: true
    volumes:
      - ./ex_scraping:/app/ex_scraping
      - ./data/db:/app/db
      - ./data/log:/app/log
  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome
    ports:
    # Selenium サーバに接続するポート
      - "4444:4444"
    # VNC で接続するポート
      - "5900:5900"
    # Selenium サーバのログを出力するポート
      - "7900:7900"
    # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info --concurrency=1
    volumes:
      - ./ex_scraping:/app/ex_scraping
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A tasks beat --loglevel=info
    volumes:
      - ./ex_scraping:/app/ex_scraping
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - redis
  flower:
    build:
      context: .
      dockerfile: flower_dockerfile
    container_name: celery_flower
    command: celery -A tasks flower --address=0.0.0.0 --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
  