services:
  search2kakaku:
    build: ./
    tty: true
    init: true
    volumes:
      - ./search2kakaku:/app/search2kakaku
      - ./data/db:/app/db
      - ./data/log:/app/log
  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info --concurrency=1
    volumes:
      - ./search2kakaku:/app/search2kakaku
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A tasks beat --loglevel=info
    volumes:
      - ./search2kakaku:/app/search2kakaku
      - ./data/db:/app/db
      - ./data/log:/app/log
    depends_on:
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_flower
    command: celery -A tasks flower --address=0.0.0.0 --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - ./search2kakaku:/app/search2kakaku
    depends_on:
      - redis
      - celery_worker